### ISSUE TITLE
Months Diplayed Backwards on Dashboard Graph

### ISSUE THREAD

**Issue by djstein** [ITNG/accounting#25]
The months for a Fiscal Year are being displayed backwards on the Dashboard Graph. They should go from July to June. Current thoughts are a quick filter by datetime on the query will ensure the months objects are ordered correctly.

**Comment by djstein** [comment]
change on line 48:
            self.months = Month.objects.filter(fiscal_year=fiscal_year).order_by('month')
order by months when filtering all months, check if this works tomorrow

**Comment by jcbassomatic** [comment]
still backwards

but the values in the plot seem ok:

![screenshot_2016-09-22_17-36-54](https://cloud.githubusercontent.com/assets/1015323/18767121/6387f71e-80eb-11e6-9e18-7e0b541efd04.png)
