### ISSUE TITLE
july monthly summary is incorrect

### ISSUE THREAD

**Issue by jcbassomatic** [ITNG/accounting#35]
example: https://lab.oscar.ncsu.edu/accounting/business_unit/8/dashboard/8/273/

Note how july'16 starting cash is the same as june'17 cash. What?

**Comment by Subzidion** [comment]
We do not have access to view the business unit (yay, permissions are working!) So you'll need to add me (chhiltbr) as a viewer, or take a screencap for us to see it.

**Comment by jcbassomatic** [comment]
![screenshot_2016-09-27_17-37-15](https://cloud.githubusercontent.com/assets/1015323/18892887/6c94159e-84d9-11e6-904e-2b7b52cb86c5.png)

**Comment by jcbassomatic** [comment]
just added chhiltbr as a manager

**Comment by jcbassomatic** [comment]
this issue went away with latest rewrite
