### ISSUE TITLE
contracts need more attribute fields

### ISSUE THREAD

**Issue by jcbassomatic** [ITNG/accounting#47]
The contracts should have a way to describe the following:
- Contract ID
- Description (ie, Development work for the NExS CIF grant)
- Contract name (ie, NExS CIF development)
- Customer (ie, DELTA 7 account)
- Notes (ie, send IDT to Jane in DELTA and reference acct 749459)

**Comment by rpkilby** [comment]
For now, these fields should only be editable while the contract is new.
